spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shivani_labs
    password: welcome
    username: root
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
