spring:
  datasource:
    url: jdbc:mysql://aa171dqbooxaeua.cppf8kcvjcko.ap-south-1.rds.amazonaws.com:3306/ebdb
    password: rootuser
    username: root
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
server:  port: 5000